### PR TITLE
[JENKINS-43189] Add the git executable to the JavaContainer for ATH tests

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
[JENKINS-43189](https://issues.jenkins-ci.org/browse/JENKINS-43189) Add the git executable to the JavaContainer for ATH tests using Java and Git

### CODE REVIEW

**Comment by jglick** [comment]
IMO this does not belong here. `GitContainer` in `acceptance-test-harness` can be extended to include a JRE if necessary.

**Comment by jglick** [comment]
Or make a `JavaGitContainer` extending `JavaContainer` and mixing in Git client support.

**Comment by cyrille-leclerc** [comment]
@jglick ack

**Comment by olivergondza** [comment]
@glick, what is the difference between adding git to `JavaContainer` and adding java to `GitContainer`, or why do you prefer the later? Note that `GitContainer` is here to do the *server* part so patching/extending git server to work as Jenkins agent to support git client and java sounds quite clumsy to me. `JavaGitContainer` would have a name misleading as it would not be a git server container.

**Comment by cyrille-leclerc** [comment]
I am working on a PR on the Pipeline Maven Plugin that is introducing a JavaGitContainer in the plugin project. If it works well, we may then refactor it.

https://github.com/jenkinsci/pipeline-maven-plugin/pull/33/files#diff-95429c4a0880ce01cdfff5df6a57babcR1

**Comment by glick** [comment]
@olivergondza you mean @jglick ;)

**Comment by olivergondza** [comment]
Err, right.

**Comment by cyrille-leclerc** [comment]
FYI I have implemented my own JavaGitContainer

https://github.com/jenkinsci/pipeline-maven-plugin/blob/87568088f87b5da4e5fbf36a0ccafd3fc1f785f0/jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/JavaGitContainer/Dockerfile

**Pull request closed without merging**
