### PR TITLE
Basic support for custom networks

### PR DESCRIPTION
**Pull request by raul-arabaolaza**
This change adds limited support for custom networks in docker-fixtures, allowing for example to launch the ATH with a docker compose file like this one:

```
version: '3'
services:
  firefox:
    image: '${SELENIUM_CONTAINER}:${SELENIUM_CONTAINER_VERSION}'
    networks:
      - ath-network
    ports:
      - '5900:5900'
      - '4444:4444'
    container_name: firefox
    environment:
      - SCREEN_WIDTH:1680
      - SCREEN_HEIGHT:1090
  mvn:
    container_name: mvn
    networks:
      - ath-network
    shm_size: '2gb'
    image: '${MAVEN_CONTAINER}:${MAVEN_CONTAINER_VERSION}'
    ports:
      - '5005:5005'
    working_dir: /src
    command: >
      bash -c "mvn test ${MAVEN_ARGS}"
    volumes:
      - ./pom.xml:/src/pom.xml
      - ./src:/src/src
      - ./.mvn:/src/.mvn
      - ./config.groovy:/src/config.groovy
      - ${WAR_FILE}:/src/jenkins.war
      - ${MAVEN_EXCLUDES_FILE}:${EXCLUDES_DESTINATION}
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MAVEN_FOLDER}:/root/.m2
      - ${MAVEN_SETTINGS_FILE}:${CUSTOM_SETTINGS_DESTINATION}
    environment:
      - DISPLAY=:0
      - RECORDER=off
      - BROWSER=remote-webdriver-firefox
      - REMOTE_WEBDRIVER_URL=http://firefox:4444/wd/hub
      - JENKINS_LOCAL_HOSTNAME=mvn
      - CONFIG=config.groovy
      - MAVEN_OPTS=-Xmx512m -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XshowSettings:vm
      - SHARED_DOCKER_SERVICE=true
      - DOCKER_FIXTURES_NETWORK=ath-network
    depends_on:
      - firefox
networks:
  ath-network:
    name: ath-network
    attachable: true
```
 
Compose file ~~copied~~ inspired by @jglick work :trollface: 

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by raul-arabaolaza** [comment]
I see no test that actually launches the fixtures, I have tested this manually by using the aforementioned docker-compose file with a custom version of the ath

**Comment by raul-arabaolaza** [comment]
cc @olivergondza apparently you are the last one merging things here :grin:

**Review by oleg-nenashev — APPROVED** [review]
No objections. Not sure using EnvVars is the best approach, but whatever works

**Review by jglick — APPROVED** [review]
Sure? This will only take effect when the test or harness picks up this PR though, of course.

Consider this lib deprecated in favor of testcontainers.org.

**Comment by jglick** [comment]
https://github.com/jenkinsci/docker-fixtures/releases/tag/docker-fixtures-1.11

**Comment by raul-arabaolaza** [comment]
:thankyou:

**Pull request merged**
